spring.datasource.url=jdbc:sqlserver://prod-server:1433;databaseName=baitapthuctap;encrypt=true;trustServerCertificate=true;
spring.datasource.username=prod_user
spring.datasource.password=prod_pass
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

server.port=8080